[tox]
description = Default tox environments list
envlist =
    code-style,type-check,tests,doc
skip_missing_interpreters = true
isolated_build = true
requires =
    tox-uv>=1

[testenv]
description = Checks for project unit tests and coverage (if desired)
runner = uv-venv-lock-runner
basepython =
    tests310: python3.10
    tests311: python3.11
    tests312: python3.12
    tests313: python3.13
    {code-style,type-check,tests,doc}: python3
passenv =
    GRANTA_MI_VERSION
setenv =
    PYTHONUNBUFFERED = yes
    PYTEST_EXTRA_ARGS = --mi-version={env:GRANTA_MI_VERSION} --cov=ansys.grantami.system --cov-report=term --cov-report=xml:.cov/xml --cov-report=html:.cov/html
commands =
    pytest {env:PYTEST_MARKERS:} {env:PYTEST_EXTRA_ARGS:} {posargs:-vv}

[testenv:code-style]
description = Checks project code style
runner = uv-venv-runner
skip_install = true
deps =
    pre-commit-uv>=4.2.0
commands =
    pre-commit run --all-files --show-diff-on-failure

[testenv:type-check]
description = Run type checking with mypy
runner = uv-venv-lock-runner
commands =
    mypy {posargs:src}

[testenv:doc]
description = Check if documentation generates properly
dependency_groups = doc
runner = uv-venv-lock-runner
passenv =
    BUILD_EXAMPLES
commands =
    sphinx-build -d "{toxworkdir}/doc_doctree" doc/source "{toxinidir}/doc/_build/html" --color -W -bhtml -n --keep-going